# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KYWKC4YZMIpqGukZMwSxu_NisUBq5lyk
"""

def where_am_i(n):
    for i in range(142):
       if i*(i+1)/2 < n and (i+1)*(i+2)/2 >= n:\
          return (i+1, int(n - i*(i+1)/2))


T = int(input())

for test_case in range(1, T + 1):
    minji, tr = map(int, input().split())
    start_r, start_c = where_am_i(min(minji, tr))
    goal_r, goal_c = where_am_i(max(minji, tr))
    road_r, road_c = abs(start_r - goal_r), abs(start_c - goal_c)
    if start_c > goal_c:
        print(f"#{test_case} {road_r + road_c}")
    else:
        print(f"#{test_case} {max(road_r, road_c)}")